baseURL = "https://olekstomek.github.io"
languageCode = "en"
defaultContentLanguage = "en"
title = "Hallo"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Tomek"

[params]
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:mail@example.org"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/olekstomek"

    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/"
      